fixtures:
  forge_modules:
    reboot: "puppetlabs/reboot"
  symlinks:
    "dsc": "#{source_dir}"
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
