---
.gitignore:
  paths:
    - bin
    - import
    - .tmp
    - .rbenv-gemsets
    - .ruby-version
    - "*.lock"
    -  "!build/vendor/"

Gemfile:
  required:
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw
      - gem: beaker-testmode_switcher
        version: '~> 0.4'
      - gem: master_manipulator
      - gem: puppet-blacksmith
        version: '~> 3.4'
  optional:
    ':build':
      - gem: cim
      - gem: mof
        git: 'https://github.com/puppetlabs/mof.git'
        ref: 'f50581901c53ff6a40c54b72ef5f4fcaed9679a1'
      - gem: charlock_holmes
      - gem: iconv
        version: '~> 1.0.4'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.0')"
    ':development':
      - gem: 'rspec-puppet'
        platforms: ["mswin", "mingw", "x64_mingw"]
        version: '< 2.6.0'

.rubocop.yml:
  default_configs:
    selected_profile: off
    inherit_from: .rubocop_todo.yml
    require:
      - rubocop-i18n
      - rubocop-rspec

# The rakefile is heavily modified for the build process
Rakefile:
  unmanaged: true

spec/default_facts.yml:
  unmanaged: true

# We've modified the appveyor.yml significantly in order to run acceptance tests
appveyor.yml:
  unmanaged: true

.gitignore:
  required:
    - ---.project

.gitlab-ci.yml:
  delete: true
